AWSTemplateFormatVersion: 2010-09-09
Description: Application for the import of CSV files to Thetis IMS
Transform:
- AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: thetis-ims-csv-import
    Description: Application for import of CSV files to Thetis IMS
    Author: thetis-apps
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/4612b8d5aa75b9b9936c9b7b9e6c7e82
    ReadmeUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/cc41721d6a120c4745830857b2e825e8
    Labels:
    - thetis-ims
    HomePageUrl: https://github.com/thetis-apps/CSVImport
    SemanticVersion: 2.0.4
    SourceCodeUrl: https://github.com/thetis-apps/CSVImport
Parameters:
  ContextId:
    Type: String
    Description: Context that this application is handling events for.
  ClientId:
    Description: Key of the parameter that has your Thetis client id as its value.
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientId
  ClientSecret:
    Description: Key of the parameter that has your Thetis client secret as its value.
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientSecret
  ApiKey:
    Description: The api key that gives access to the context in Thetis IMS.
    Type: String
    MinLength: 1
  DevOpsEmail:
    Description: The email address to send mail to when messages in the dead letter
      queue.
    Type: String
    MinLength: 4
Globals:
  Function:
    Runtime: nodejs16.x
Resources:
  InitResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - InitializeFunction
        - Arn
      Version: 11
    Metadata:
      SamResourceId: InitResource
  InitializeFunction:
    Type: AWS::Serverless::Function
    DeletionPolicy: Delete
    Properties:
      Handler: src/handlers/csv-import.initializer
      MemorySize: 2048
      Timeout: 30
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
          ContextId:
            Ref: ContextId
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/772f22445ca86444ed35b48e512983fa
    Metadata:
      SamResourceId: InitializeFunction
  DispatchQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 360
      FifoQueue: true
      KmsMasterKeyId: alias/aws/sqs
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
          - DispatchDeadLetterQueue
          - Arn
        maxReceiveCount: 300
    Metadata:
      SamResourceId: DispatchQueue
  FileAttachedEventHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: Function that runs when a CSV file is attached.
      Handler: src/handlers/csv-import.fileAttachedEventHandler
      Policies:
      - AmazonSQSFullAccess
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
          DispatchQueue:
            Ref: DispatchQueue
      Events:
        Request:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
              - public.thetis-ims.com
              detail-type:
              - fileAttached
              detail:
                contextId:
                - Ref: ContextId
      MemorySize: 2048
      Timeout: 900
      DeadLetterQueue:
        Type: SQS
        TargetArn:
          Fn::GetAtt:
          - DeadLetterQueue
          - Arn
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/772f22445ca86444ed35b48e512983fa
    Metadata:
      SamResourceId: FileAttachedEventHandler
  Writer:
    Type: AWS::Serverless::Function
    Properties:
      Description: Function POST data to Thetis IMS.
      Handler: src/handlers/csv-import.writer
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
          DispatchQueue:
            Ref: DispatchQueue
      Events:
        Request:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - DispatchQueue
              - Arn
      MemorySize: 2048
      Timeout: 300
      ReservedConcurrentExecutions: 10
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/772f22445ca86444ed35b48e512983fa
    Metadata:
      SamResourceId: Writer
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: alias/aws/sqs
    Metadata:
      SamResourceId: DeadLetterQueue
  DispatchDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
    Metadata:
      SamResourceId: DispatchDeadLetterQueue
