AWSTemplateFormatVersion: 2010-09-09
Description: Application for the import of CSV files to Thetis IMS
Transform:
- AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: thetis-ims-csv-import
    Description: Application for import of CSV files to Thetis IMS
    Author: thetis-apps
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/4612b8d5aa75b9b9936c9b7b9e6c7e82
    ReadmeUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/fef8798cc87c9cc06bd5318ee5e7717c
    Labels:
    - thetis-ims
    HomePageUrl: https://github.com/thetis-apps/CSVImport
    SemanticVersion: '0.0.3'
    SourceCodeUrl: https://github.com/thetis-apps/CSVImport
Parameters:
  ContextId:
    Type: String
    Description: Context that this application is handling events for.
  ClientId:
    Description: Key of the parameter that has your Thetis client id as its value.
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientId
  ClientSecret:
    Description: Key of the parameter that has your Thetis client secret as its value.
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientSecret
  ApiKey:
    Description: The api key that gives access to the context in Thetis IMS.
    Type: String
    MinLength: 1
  DevOpsEmail:
    Description: The email address to send mail to when messages in the dead letter
      queue.
    Type: String
    MinLength: 4
Resources:
  DispatchQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300
  FileAttachedEventHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: Function that runs when a CSV file is attached.
      Runtime: nodejs12.x
      Handler: src/handlers/csv-import.fileAttachedEventHandler
      Policies:
      - AmazonSQSFullAccess
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
          DispatchQueue:
            Ref: DispatchQueue
      Events:
        Request:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
              - public.thetis-ims.com
              detail-type:
              - fileAttached
              detail:
                contextId:
                - Ref: ContextId
      MemorySize: 2048
      Timeout: 300
      DeadLetterQueue:
        Type: SQS
        TargetArn:
          Fn::GetAtt:
          - DeadLetterQueue
          - Arn
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/4f62453af146859ef3d2326b4b4095fe
  Writer:
    Type: AWS::Serverless::Function
    Properties:
      Description: Function POST data to Thetis IMS.
      Runtime: nodejs12.x
      Handler: src/handlers/csv-import.writer
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
          DispatchQueue:
            Ref: DispatchQueue
      Events:
        Request:
          Type: SQS
          Properties:
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 10
            Queue:
              Fn::GetAtt:
              - DispatchQueue
              - Arn
      MemorySize: 256
      Timeout: 300
      DeadLetterQueue:
        Type: SQS
        TargetArn:
          Fn::GetAtt:
          - DeadLetterQueue
          - Arn
      ReservedConcurrentExecutions: 5
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/4f62453af146859ef3d2326b4b4095fe
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties: {}
  Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm when any message is moved to the dead letter queue.
      AlarmActions:
      - Ref: IncidentTopic
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      MetricName: ApproximateNumberOfMessagesVisible
      Period: 60
      Namespace: AWS/SQS
      Threshold: '0'
      Unit: Count
      Dimensions:
      - Name: QueueName
        Value:
          Fn::GetAtt:
          - DeadLetterQueue
          - QueueName
      TreatMissingData: notBreaching
      Statistic: Maximum
  IncidentTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint:
          Ref: DevOpsEmail
        Protocol: email
      DisplayName: Incidents to be handled by Thetis Devops.
